# Generated by Django 5.0.7 on 2024-07-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cuenta',
        ),
    ]
